# Generated by Django 5.2.8 on 2025-12-28 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('listen_port', models.PositiveIntegerField(blank=True, null=True)),
                ('fwmark', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=44)),
                ('persistent_keepalive', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='wireguardapp.interface')),
            ],
        ),
        migrations.CreateModel(
            name='PeerAllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=64)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_ips', to='wireguardapp.peer')),
            ],
        ),
        migrations.CreateModel(
            name='PeerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('handshake', 'Handshake'), ('handshake_failed', 'Handshake Failed'), ('interface_up', 'Interface Up'), ('interface_down', 'Interface Down'), ('unknown', 'Unknown')], max_length=32)),
                ('message', models.TextField()),
                ('event_time', models.DateTimeField(db_index=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='wireguardapp.interface')),
                ('peer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='wireguardapp.peer')),
            ],
        ),
        migrations.CreateModel(
            name='PeerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(blank=True, max_length=64, null=True)),
                ('latest_handshake', models.DateTimeField(blank=True, null=True)),
                ('rx_bytes', models.BigIntegerField()),
                ('tx_bytes', models.BigIntegerField()),
                ('collected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='wireguardapp.peer')),
            ],
        ),
        migrations.AddIndex(
            model_name='peer',
            index=models.Index(fields=['interface', 'public_key'], name='wireguardap_interfa_642b72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together={('interface', 'public_key')},
        ),
        migrations.AddIndex(
            model_name='peerallowedip',
            index=models.Index(fields=['peer', 'cidr'], name='wireguardap_peer_id_a7963b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='peerallowedip',
            unique_together={('peer', 'cidr')},
        ),
        migrations.AddIndex(
            model_name='peersnapshot',
            index=models.Index(fields=['peer', 'collected_at'], name='wireguardap_peer_id_969e51_idx'),
        ),
    ]
