# Generated by Django 5.2.8 on 2026-01-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='public_key',
            field=models.CharField(max_length=44, null=True),
        ),
    ]
