# Generated by Django 5.2.8 on 2026-01-07 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0002_interface_public_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=44, unique=True)),
                ('private_key', models.CharField(max_length=44, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='peer',
            new_name='wireguardap_interfa_1af59f_idx',
            old_name='wireguardap_interfa_642b72_idx',
        ),
        migrations.AddField(
            model_name='keys',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interface',
            name='public_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wireguardapp.keys'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peer',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wireguardapp.keys'),
        ),
    ]
