# Generated by Django 5.2.8 on 2026-01-07 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0004_rename_keys_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfacekey', to='wireguardapp.key'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peerkey', to='wireguardapp.key'),
        ),
    ]
