# Generated by Django 5.2.8 on 2026-01-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0005_alter_interface_public_key_alter_peer_public_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='peerallowedip',
            name='wireguardap_peer_id_a7963b_idx',
        ),
        migrations.RemoveIndex(
            model_name='peersnapshot',
            name='wireguardap_peer_id_969e51_idx',
        ),
        migrations.AlterUniqueTogether(
            name='peerallowedip',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='key',
            name='key_type',
            field=models.CharField(choices=[('server', 'Server'), ('client', 'CLient')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
