# Generated by Django 5.2.8 on 2026-01-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0006_remove_peerallowedip_wireguardap_peer_id_a7963b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key_type',
            field=models.CharField(choices=[('server', 'Server'), ('client', 'Client')], max_length=64),
        ),
    ]
