# Generated by Django 5.2.8 on 2026-01-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0007_alter_key_key_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WireguardServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wireguardapp.interface')),
                ('public_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wireguardapp.key')),
            ],
        ),
    ]
