# Generated by Django 5.2.8 on 2026-02-04 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0007_alter_key_key_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='key_type',
        ),
        migrations.AddField(
            model_name='interface',
            name='ip_address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='peer_type',
            field=models.CharField(choices=[('server', 'Server'), ('client', 'Client')], default='server', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peer',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peerkey', to='wireguardapp.key', verbose_name='Connected to interface'),
        ),
    ]
