# Generated by Django 5.2.8 on 2026-01-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0008_wireguardserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='key_type',
        ),
        migrations.AddField(
            model_name='peer',
            name='ip_address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='peer',
            name='peer_type',
            field=models.CharField(choices=[('server', 'Server'), ('client', 'Client')], max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='WireguardServer',
        ),
    ]
