# Generated by Django 5.2.8 on 2026-02-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0008_remove_key_key_type_interface_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='peer_type',
        ),
        migrations.AddField(
            model_name='interface',
            name='interface_type',
            field=models.CharField(choices=[('server', 'Server'), ('client', 'Client')], default='server', max_length=32),
            preserve_default=False,
        ),
    ]
