# Generated by Django 5.2.8 on 2026-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0009_remove_peer_peer_type_interface_interface_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='interface_type',
            field=models.CharField(choices=[('server', 'Server'), ('client', 'Client')], max_length=32, null=True),
        ),
    ]
