# Generated by Django 5.2.8 on 2026-01-30 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0009_remove_key_key_type_peer_ip_address_peer_peer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peerkey', to='wireguardapp.key', verbose_name='interface connected to'),
        ),
    ]
