# Generated by Django 5.2.8 on 2026-02-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0010_alter_interface_interface_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='public_key',
            new_name='interface_key',
        ),
    ]
