# Generated by Django 5.2.8 on 2026-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0010_alter_peer_public_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='ip_address',
        ),
        migrations.AddField(
            model_name='interface',
            name='ip_address',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='peer',
            name='peer_type',
            field=models.CharField(choices=[('server', 'Server'), ('client', 'Client')], max_length=32),
        ),
    ]
