# Generated by Django 5.2.8 on 2026-02-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0011_rename_public_key_interface_interface_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='peer',
            name='wireguardap_interfa_1af59f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='peer',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peerkey', to='wireguardapp.key'),
        ),
    ]
