# Generated by Django 5.2.8 on 2026-02-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0012_remove_peer_wireguardap_interfa_1af59f_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peer',
            old_name='public_key',
            new_name='peer_key',
        ),
    ]
