# Generated by Django 5.2.8 on 2026-02-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0013_rename_public_key_peer_peer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='interface_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wireguardapp.key'),
        ),
    ]
