# Generated by Django 5.2.8 on 2026-02-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0014_alter_interface_interface_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='wireguardapp.interface', verbose_name='Interface included with this peer'),
        ),
    ]
