# Generated by Django 5.2.8 on 2026-02-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0015_alter_peer_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='peer_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peerkey', to='wireguardapp.key', verbose_name='Connected to'),
        ),
    ]
