# Generated by Django 5.2.8 on 2026-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0016_alter_peer_peer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
