# Generated by Django 5.2.8 on 2026-02-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0017_alter_interface_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='server_endpoint',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
