# Generated by Django 5.2.8 on 2026-02-12 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0018_interface_server_endpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeerAllowedIP',
        ),
    ]
