# Generated by Django 5.2.8 on 2026-02-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0019_delete_peerallowedip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='private_key',
            field=models.TextField(),
        ),
    ]
