# Generated by Django 5.2.8 on 2026-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0022_alter_key_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='session_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='peer',
            name='total_rx_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peersnapshot',
            name='session',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
