# Generated by Django 5.2.8 on 2026-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0023_interface_session_number_peer_total_rx_bytes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='total_tx_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
