# Generated by Django 5.2.8 on 2026-02-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0024_peer_total_tx_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='last_rx_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='peer',
            name='last_tx_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
