# Generated by Django 5.2.8 on 2026-03-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0027_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key_limit',
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
