# Generated by Django 5.2.8 on 2026-03-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0028_profile_key_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='key_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
