# Generated by Django 5.2.8 on 2026-03-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0029_profile_key_count_alter_profile_key_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer',
            name='peer_key',
        ),
        migrations.AddField(
            model_name='peer',
            name='peer_interface',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='peer', to='wireguardapp.interface', verbose_name='Connected to'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peer',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_interface', to='wireguardapp.interface', verbose_name='Interface included with this peer'),
        ),
        migrations.AlterField(
            model_name='peersnapshot',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wireguardapp.peer'),
        ),
    ]
