# Generated by Django 5.2.8 on 2026-03-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0030_remove_peer_peer_key_peer_peer_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='ip_address',
            field=models.CharField(max_length=32),
        ),
    ]
