# Generated by Django 5.2.8 on 2026-03-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0031_alter_interface_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='fwmark',
        ),
    ]
