# Generated by Django 5.2.8 on 2026-03-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0032_remove_interface_fwmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='ip_network',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
