# Generated by Django 5.2.8 on 2026-03-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0033_interface_ip_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='ip_network_mask',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
