# Generated by Django 5.2.8 on 2026-03-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0034_interface_ip_network_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='ip_network_mask',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
