# Generated by Django 5.2.8 on 2026-03-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0036_alter_interface_ip_network_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='interface_type',
            field=models.CharField(choices=[('server', 'Server'), ('client', 'Client')], max_length=32),
        ),
        migrations.AlterField(
            model_name='interface',
            name='ip_network_mask',
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
