# Generated by Django 5.2.8 on 2026-03-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0037_alter_interface_interface_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='ip_network_mask',
            field=models.PositiveIntegerField(),
        ),
    ]
