# Generated by Django 5.2.8 on 2026-03-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0038_alter_interface_ip_network_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='current_clienttoclient_state',
            field=models.BooleanField(default=False, verbose_name='Allow clients to connect to each other?'),
        ),
        migrations.AddField(
            model_name='interface',
            name='current_internet_interface',
            field=models.CharField(default=0, max_length=64, verbose_name='Current internet interface'),
            preserve_default=False,
        ),
    ]
