# Generated by Django 5.2.8 on 2026-03-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wireguardapp', '0039_interface_current_clienttoclient_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='current_clienttoclient_state',
            new_name='client_to_client',
        ),
    ]
