from wireguardapp.models import Interface, Peer, PeerSnapshot, Key
from django.contrib.auth.models import User
from .wireguard import generateKeyPair
from .crypto import encrypt_value,decrypt_value
import ipaddress
import re
from django.utils import timezone
from django.db import transaction

KEEPALIVE = 25
PORT =      51820  



def allocateIpaddress(serverInterface:Interface):
    """
    Allocates an ip address based on a given server interface
    
    
    :param serverInterface: interface of a server in a form for example 10.0.0.1/24.
    :type serverInterface: Interface

    :return: ip adrress with bit mask (e.g. 10.0.0.12/32)
    :rtype: str 


    :raise TypeError: Raised if the given interface type does not have interface_type = 'server'
    :raise ValueError: Raised if there are no available ip addresses from the server interface.
    """
    if (serverInterface.interface_type != Interface.SERVER):
        raise TypeError
    
    interface = ipaddress.ip_interface(serverInterface.ip_address)
    base = interface.network

    clientInterfaces = Interface.objects.filter(interface_type = Interface.CLIENT).values_list('ip_address',flat=True)
    occupied = {ipaddress.IPv4Interface(i).ip for i in clientInterfaces}
    occupied.add(interface.ip)

    for ip in base.hosts():
        if ip not in occupied:
            return f'{ip}/32'

    raise ValueError


def createNewKey(user : User, name: str = None) -> Key:
    """
    Creates a Key object generated by 'wg genkey' and 'wg pubkey <private_key>' commands
    
    :param user: The key object will be generated for this user
    :type user: User

    :param name: Name of this key. Used to identify the key for the user e.g. 'My key for my notebook'.
    Does not affect wireguard config or commands.
    :type name: str


    :return: Returns the created and unsaved key.
    :rtype: Key
    """
    privateKey, publicKey = generateKeyPair()
    newkey = Key(
        user = user,
        private_key = encrypt_value(privateKey),
        public_key = publicKey,
        name = name
    )

    return newkey
    

def createClientInterface(user : User,key : Key, serverInterface :Interface) -> Interface:
    """
    Creates a Interface object for a client, 
    with an allocated ip address from a server network address.
    
    :param user: Makes a name for the interface with arg name
    :type user: User

    :param key: Key for this interface
    :type key: Key

    :param serverInterface: For allocation of a ip address based on this server interface ip interface
    :type serverInterface: Interface

    :return: Returns the created and unsaved interfaces
    :rtype: Interface
    """
    interfaceName = user.username + '-' + str(timezone.datetime.now())
    interface = Interface(
        name = interfaceName,
        interface_key = key,
        ip_address = allocateIpaddress(serverInterface),
        interface_type = Interface.CLIENT
    )

    return interface

def makeServerNewName() -> str:
    """
    Provides a unique name for a server interface.
    Creates a name in a form `wg-server{num}`.

    :return: Generated name for the server interface.
    :rtype: str
    """

    names = Interface.objects.filter(interface_type = Interface.SERVER).values_list('name',flat=True)
    nums = [int(re.search(r'\d+',x).group()) for x in names]

    num = max(nums,default=-1)

    return f'wg{num+1}'

def createServerInterface(key : Key, ipNetwork : str, endpoint : str, port : str):
    """
    Creates a Interface object for a server interface.
    Execute when there is no server interface yet.
    
    
    :param key: Key for this interface
    :type key: Key

    :param ipNetwork: The network of the new server interface. Has a form `10.10.1.0/24`
        Will select first available ip address interface from the network.
    :type ipNetwork: str

    :param endpoint: Server will use this endpoint to generate wireguard client configuration files.
    :type endpoint: str

    :param port: Port of the server interface between 0 and 65535.
    :type port: str

    :return: Returns the created and unsaved interfaces
    :rtype: Interface

    :raises ValueError: if .
    """
    # not correct format -> error
    network = ipaddress.ip_network(ipNetwork)
    address = next( network.hosts())
    interface = ipaddress.ip_interface(f"{address}/{network.prefixlen}")

    name = makeServerNewName()

    interface = Interface(
        name = name,
        interface_key = key,
        ip_address = interface,
        interface_type = Interface.SERVER,
        server_endpoint = endpoint,
        listen_port = port  
    )

    return interface


def createClientServerPeers(serverInterface : Interface, clientInterface : Interface):
    """
    Creates a Peer objects for the wireguard interfaces. 
    For the server and client interface, create a peer object based on a wireguard configuration.
    Their functionality is based on their interface type.

    :param serverInterface: Interface to add a peer object for client. Wont have keepalive.
    :type serverInterface: Interface
    
    :param clientInterface: Interface to connect to server. Interface will have a one peer object connected to server.
    :type clientInterface: Interface

    :return: Returns client and server peer objects
    :rtype: tuple[Peer,Peer]
    """

    clientPeer = Peer(
        interface = clientInterface,
        peer_key = serverInterface.interface_key,
        persistent_keepalive = KEEPALIVE
    )
    serverPeer = Peer(
        interface = serverInterface,
        peer_key = clientInterface.interface_key,
    )
    return clientPeer,serverPeer
    



