from wireguardapp.models import Interface, Peer, PeerSnapshot, Key,Profile
from django.contrib.auth.models import User
from .wireguard.wireguardcmd import generateKeyPair
from .crypto import encrypt_value,decrypt_value
from wireguardapp.database.selectors.selector import selectInterfacesFromServerInterface
import ipaddress
import re
from django.utils import timezone
from django.db import transaction

KEEPALIVE = 25
PORT =      51820  



def allocateIpaddress(serverInterface:Interface):
    """
    Allocates an ip address based on a given server interface
    
    
    :param serverInterface: The inteface to allocate an ip address from its network.
    :type serverInterface: Interface

    :return: An ip adrress(e.g. 10.0.0.12)
    :rtype: str 

    :raise TypeError: Raised if the given interface type does not have interface_type = 'server'
    :raise ValueError: Raised if there are no available ip addresses from the server interface.
    """
    if (serverInterface.interface_type != Interface.SERVER):
        raise TypeError
    
    interfaceNetwork = ipaddress.ip_network(f"{serverInterface.ip_network}/{serverInterface.ip_network_mask}")
    base = interfaceNetwork

    
    clientInterfacesIps = selectInterfacesFromServerInterface(serverInterface=serverInterface)
    occupied = {ipaddress.IPv4Address(i.ip_address) for i in clientInterfacesIps}
    occupied.add(ipaddress.IPv4Address(serverInterface.ip_address))

    for ip in base.hosts():
        if ip not in occupied:
            return f'{ip}'

    raise ValueError


def createNewKey(user : User, name: str = None) -> Key:
    """
    Creates a Key object generated by 'wg genkey' and 'wg pubkey <private_key>' commands
    
    :param user: The key object will be generated for this user
    :type user: User

    :param name: Name of this key. Used to identify the key for the user e.g. 'My key for my notebook'.
    Does not affect wireguard config or commands.
    :type name: str


    :return: Returns the created and unsaved key.
    :rtype: Key
    """
    privateKey, publicKey = generateKeyPair()
    newkey = Key(
        user = user,
        private_key = encrypt_value(privateKey),
        public_key = publicKey,
        name = name
    )

    return newkey
    

def createClientInterface(user : User,key : Key, serverInterface :Interface) -> Interface:
    """
    Creates a Interface object for a client, 
    with an allocated ip address from a server network address.
    
    :param user: Makes a name for the interface with arg name
    :type user: User

    :param key: Key for this interface
    :type key: Key

    :param serverInterface: For allocation of a ip address based on this server interface ip interface
    :type serverInterface: Interface

    :return: Returns the created and unsaved interfaces
    :rtype: Interface
    """
    interfaceName = user.username + '-' + str(timezone.datetime.now())
    interface = Interface(
        name = interfaceName,
        interface_key = key,
        ip_address = allocateIpaddress(serverInterface),
        ip_network_mask = 32,
        interface_type = Interface.CLIENT
    )

    return interface

def makeServerNewName() -> str:
    """
    Provides a unique name for a server interface.
    Creates a name in a form `wg-server{num}`.

    :return: Generated name for the server interface.
    :rtype: str
    """

    names = Interface.objects.filter(interface_type = Interface.SERVER).values_list('name',flat=True)
    nums = [int(re.search(r'\d+',x).group()) for x in names]

    num = max(nums,default=-1)

    return f'wg{num+1}'

def createServerInterface(key : Key, ipNetwork : str, netMask : str, endpoint : str, port : str):
    """
    Creates a Interface object for a server interface.
    Execute when there is no server interface yet.
    
    
    :param key: Key for this interface
    :type key: Key

    :param ipNetwork: The network of the new server interface. Has a form `10.10.1.0/24`
        Will select first available ip address interface from the network.
    :type ipNetwork: str

    :param netMask: The netmask of the network address.
    :type netMask: str

    :param endpoint: Server will use this endpoint to generate wireguard client configuration files.
    :type endpoint: str

    :param port: Port of the server interface between 0 and 65535.
    :type port: str

    :return: Returns the created and unsaved interfaces
    :rtype: Interface

    :raises ValueError: if ip network is not in a correct format. 
    """
    # not correct format -> error
    network = ipaddress.ip_network(f"{ipNetwork}/{netMask}")
    address = next( network.hosts())

    name = makeServerNewName()

    interface = Interface(
        name = name,
        interface_key = key,
        ip_network = ipNetwork,
        ip_network_mask = netMask,
        ip_address = address,
        interface_type = Interface.SERVER,
        server_endpoint = endpoint,
        listen_port = port  
    )

    return interface


def createServerPeer(serverInterface : Interface, clientInterface : Interface) -> Peer:
    """
    Creates a Peer object for the wireguard interfaces. 

    The peer will be owned by the server interface and is connected to the client interface

    :param serverInterface: Interface to add the client to.
    :type serverInterface: Interface
    
    :param clientInterface: Interface that is connected to the server
    :type clientInterface: Interface

    :return: Returns the server peer 
    :rtype: Peer
    """

    serverPeer = Peer(
        interface = serverInterface,
        peer_interface = clientInterface,
        persistent_keepalive = KEEPALIVE
    )
    return serverPeer
    
def createProfile(user: User):
    profile = Profile(
        user=user,
        verified=False
    )
    return profile


