from wireguardapp.models import Interface, Peer, PeerSnapshot, Key
from django.contrib.auth.models import User
from .wireguard import generateKeyPair
from .crypto import encrypt_value,decrypt_value
import ipaddress
from django.utils import timezone

KEEPALIVE = 25
PORT =      51820  


def allocateIpaddress(serverInterface:Interface):
    """
    Allocates an ip address based on a given server interface
    
    
    :param serverInterface: interface of a server in a form for example 10.0.0.1/24.
    :type serverInterface: Interface

    :return: ip adrress with bit mask (e.g. 10.0.0.12/32)
    :rtype: str 


    :raise TypeError: Raised if the given interface type does not have interface_type = 'server'
    :raise ValueError: Raised if there are no available ip addresses from the server interface.
    """
    if (serverInterface.interface_type != Interface.SERVER):
        raise TypeError
    
    interface = ipaddress.ip_interface(serverInterface.ip_address)
    base = interface.network

    clientInterfaces = Interface.objects.filter(interface_type = Interface.CLIENT).values_list('ip_address',flat=True)
    occupied = {ipaddress.IPv4Interface(i).ip for i in clientInterfaces}
    occupied.add(interface.ip)

    for ip in base.hosts():
        if ip not in occupied:
            return f'{ip}/32'

    raise ValueError


def createNewKey(user : User, name: str = None) -> Key:
    """
    Creates a Key object generated by 'wg genkey' and 'wg pubkey <private_key>' commands
    
    :param user: The key object will be generated for this user
    :type user: User

    :param name: Name of this key. Used to identify the key for the user e.g. 'My key for my notebook'.
    Does not affect wireguard config or commands.
    :type name: str


    :return: Returns the created and unsaved key.
    :rtype: Key
    """
    privateKey, publicKey = generateKeyPair()
    newkey = Key(
        user = user,
        private_key = encrypt_value(privateKey),
        public_key = publicKey,
        name = name
    )

    return newkey
    

def createClientInterface(user : User,key : Key, serverInterface :Interface) -> Interface:
    """
    Creates a Interface object for a client, 
    with an allocated ip address from a server network address.
    
    :param user: Makes a name for the interface with arg name
    :type user: User

    :param key: Key for this interface
    :type key: Key

    :param serverInterface: For allocation of a ip address based on this server interface ip interface
    :type serverInterface: Interface

    :return: Returns the created and unsaved interfaces
    :rtype: Interface
    """
    interfaceName = user.username + '-' + str(timezone.datetime.now())
    interface = Interface(
        name = interfaceName,
        interface_key = key,
        ip_address = allocateIpaddress(serverInterface),
        interface_type = Interface.CLIENT
    )

    return interface

def createServerInterface(key : Key, ipinterface : str, endpoint : str):
    """
    Creates a Interface object for a server interface.
    Execute when there is no server interface yet.
    
    
    :param key: Key for this interface
    :type key: Key

    :param ipinterface: Ip interface with its own bit mask (e.g '10.0.0.2/24'). 
        will later on allocate ip addresses based on this network
        except selected ip address in the given address (e.g '10.0.0.2/32')
    :type ipinterface: str

    :param endpoint: Server will use this endpoint to generate wireguard client configuration files.
    :type endpoint: str

    :return: Returns the created and unsaved interfaces
    :rtype: Interface

    :raises ValueError: if the ipinterface is not a ip address with a bit mask.
    """
    # not correct format -> error
    ipaddress.ip_interface(ipinterface)
    name = 'wg-server'
    interface = Interface(
        name = name,
        interface_key = key,
        ip_address = ipinterface,
        interface_type = Interface.SERVER,
        server_endpoint = endpoint,
        listen_port = PORT  
    )

    return interface


def createClientServerPeers(serverInterface : Interface, clientInterface : Interface):
    """
    Creates a Peer objects for the wireguard interfaces. 
    For the server and client interface, create a peer object based on a wireguard configuration.
    Their functionality is based on their interface type.

    :param serverInterface: Interface to add a peer object for client. Wont have keepalive.
    :type serverInterface: Interface
    
    :param clientInterface: Interface to connect to server. Interface will have a one peer object connected to server.
    :type clientInterface: Interface

    :return: Returns client and server peer objects
    :rtype: tuple[Peer,Peer]
    """

    clientPeer = Peer(
        interface = clientInterface,
        peer_key = serverInterface.interface_key,
        persistent_keepalive = KEEPALIVE
    )
    serverPeer = Peer(
        interface = serverInterface,
        peer_key = clientInterface.interface_key,
    )
    return clientPeer,serverPeer
    