from wireguardapp.models import Interface, Peer, PeerSnapshot, Key
from django.contrib.auth.models import User
from .wireguard import generateKeyPair
from .crypto import encrypt_value,decrypt_value
import ipaddress
from django.utils import timezone

KEEPALIVE = 25
PORT =      51820  


def allocateIpaddress(serverInterface:Interface):
    """
    Allocates an ip address based on a given server interface
    
    Parameters:
        serverInterface (Interface): interface of a server in a form for example 10.0.0.1/24.

    Returns:
        str: ip adrress with bit mask (e.g. 10.0.0.12/32)
    Exceptions:
        TypeError: Raised if the given interface type does not have interface_type = 'server'
        ValueError: Raised if there are no available ip addresses from the server interface.
    """
    if (serverInterface.interface_type != Interface.SERVER):
        raise TypeError
    
    interface = ipaddress.ip_interface(serverInterface.ip_address)
    base = interface.network

    clientInterfaces = Interface.objects.filter(interface_type = Interface.CLIENT).values_list('ip_address',flat=True)
    occupied = {ipaddress.IPv4Interface(i).ip for i in clientInterfaces}
    occupied.add(interface.ip)

    for ip in base.hosts():
        if ip not in occupied:
            return f'{ip}/32'

    raise ValueError


def createNewKey(user : User, name: str = None):
    """
    Creates a Key object generated by 'wg genkey' and 'wg pubkey <private_key>' commands
    
    :param user: The key object will be generated for this user
    :type user: User
    :param name: Name of this key. Used to identify the key for the user e.g. 'My key for my notebook'.
    Does not affect wireguard config or commands.
    :type name: str
    """
    privateKey, publicKey = generateKeyPair()
    newkey = Key(
        user = user,
        private_key = encrypt_value(privateKey),
        public_key = publicKey,
        name = name
    )

    return newkey
    

def createClientInterface(user : User,key : Key, serverInterface :Interface):
    """
    Creates a Interface object for a client, 
    with an allocated ip address from a server network address.
    
    :param user: Makes a name for the interface with arg name
    :type user: User
    :param key: Key for this interface
    :type key: Key
    :param serverInterface: For allocation of a ip address based on this server interface ip interface
    :type serverInterface: Interface
    """
    interfaceName = user.username + '-' + str(timezone.datetime.now())
    interface = Interface(
        name = interfaceName,
        interface_key = key,
        ip_address = allocateIpaddress(serverInterface),
        interface_type = Interface.CLIENT
    )

    return interface

def createServerInterface(key : Key, ipinterface : str, endpoint : str):
    """
    Creates a Interface object for a server interface.
    Execute when there is no server interface yet.
    
    
    :param key: Key for this interface
    :type key: Key
    :param ipinterface: Ip interface with its own bit mask (e.g '10.0.0.2/24'). 
        will later on allocate ip addresses based on this network
        except selected ip address in the given address (e.g '10.0.0.2/32')
    :type ipinterface: str
    :param endpoint: Server will use this endpoint to generate wireguard client configuration files.
    :type key: str
    """
    # not correct format -> error
    ipaddress.ip_interface(ipinterface)
    name = 'wg-server'
    interface = Interface(
        name = name,
        interface_key = key,
        ip_address = ipinterface,
        interface_type = Interface.SERVER,
        server_endpoint = endpoint,
        listen_port = PORT  
    )

    return interface

# create a peer based on a interface
def createPeer(serverKey : Key, clientInterface : Interface):
    """
    Creates a Peer object based on wireguard peer. 
    The peer belongs to the interface given. Connects to the interface 
    specified on the specified by a key. 
    
    :param serverKey: Connects to an another interface with this key.
    :type serverKey: Key
    :param clientInterface: Belongs to this interface. 
        In wireguard, the created peer will be with this interface
    :type clientInterface: Interface
    """
    peer = Peer(
        interface = clientInterface,
        peer_key = serverKey,
        persistent_keepalive = KEEPALIVE
    )
    return peer
