import logging
from django.db import transaction
from django.contrib.auth.models import User
from django.utils import timezone
from collections import defaultdict

from wireguardapp.models import Interface, Peer, Key, Profile, PeerSnapshot

from .wireguardcmd import generateKeyPair
from .crypto import encrypt_value

import ipaddress
import re
import datetime
from django.utils import timezone
from wireguardapp.database.repository import InterfaceRepository



logger = logging.getLogger("wg")

KEEPALIVE = 25
PORT = 51820



# -----------------------------
# Model Creation Functions
# -----------------------------
class ModelFactory:
    # -------------------
    # IP Allocation
    # -------------------
    @staticmethod
    def allocateIpAddress(server_interface: Interface) -> str:
        """
        Allocates an ip address based on a given server interface
        
        
        :param serverInterface: The inteface to allocate an ip address from its network.
        :type serverInterface: Interface

        :return: An ip adrress(e.g. 10.0.0.12)
        :rtype: str 

        :raise TypeError: Raised if the given interface type does not have interface_type = 'server'
        :raise ValueError: Raised if there are no available ip addresses from the server interface.
        """
        if server_interface.interface_type != Interface.SERVER:
            raise TypeError("Interface není typy server.")

        network = ipaddress.ip_network(f"{server_interface.ip_network}/{server_interface.ip_network_mask}")
        clients = InterfaceRepository.getClientInterfacesFromServer(server_interface)
        occupied = {ipaddress.IPv4Address(i.ip_address) for i in clients}
        occupied.add(ipaddress.IPv4Address(server_interface.ip_address))

        for ip in network.hosts():
            if ip not in occupied:
                return str(ip)

        raise ValueError("Nejsou žádné volné ip adresy pro server.")
    @staticmethod
    def createKey(user: User, name: str = None) -> Key:
        """
        Creates a Key object generated by 'wg genkey' and 'wg pubkey <private_key>' commands
        
        :param user: The key object will be generated for this user
        :type user: User

        :param name: Name of this key. Used to identify the key for the user e.g. 'My key for my notebook'.
        Does not affect wireguard config or commands.
        :type name: str


        :return: Returns the created and unsaved key.
        :rtype: Key
        """
        private_key, public_key = generateKeyPair()
        return Key(
            user=user,
            private_key=encrypt_value(private_key),
            public_key=public_key,
            name=name
        )

    @staticmethod
    def createClientInterface(user: User, key: Key, serverInterface: Interface) -> Interface:
        """
        Creates a Interface object for a client, 
        with an allocated ip address from a server network address.
        
        :param user: Makes a name for the interface with arg name
        :type user: User

        :param key: Key for this interface
        :type key: Key

        :param serverInterface: For allocation of a ip address based on this server interface ip interface
        :type serverInterface: Interface

        :return: Returns the created and unsaved interfaces
        :rtype: Interface
        """
        interface_name = f"{user.username}-{timezone.datetime.now().strftime('%Y%m%d%H%M%S')}"
        ip_address = ModelFactory.allocateIpAddress(serverInterface)
        return Interface(
            name=interface_name,
            interface_key=key,
            ip_address=ip_address,
            ip_network_mask=32,
            interface_type=Interface.CLIENT
        )

    @staticmethod
    def createServerInterface(key: Key, ipNetwork: str, netmask: str, endpoint: str, port: str,clientToClient : bool) -> Interface:
        """
        Creates a Interface object for a server interface.
        
        :param key: Key for this interface, User should be null, since a server interface does not have a owner.
        :type key: Key

        :param ipNetwork: The network of the new server interface. Has a form `10.10.1.0/24`
            Will select first available ip address interface from the network.
        :type ipNetwork: str

        :param netMask: The netmask of the network address.
        :type netMask: str

        :param endpoint: Server will use this endpoint to generate wireguard client configuration files.
        :type endpoint: str

        :param port: Port of the server interface between 0 and 65535.
        :type port: str

        :return: Returns the created and unsaved interfaces
        :rtype: Interface

        :raises ValueError: if ip network is not in a correct format. 
        """
        network = ipaddress.ip_network(f"{ipNetwork}/{netmask}")
        address = next(network.hosts())
        name = ModelFactory.makeServerNewName()
        return Interface(
            name=name,
            interface_key=key,
            ip_network=ipNetwork,
            ip_network_mask=netmask,
            ip_address=address,
            interface_type=Interface.SERVER,
            server_endpoint=endpoint,
            listen_port=port,
            client_to_client=clientToClient,
        )

    @staticmethod
    def createPeer(serverInterface: Interface, clientInterface: Interface) -> Peer:
        """
        Creates a Peer object for the wireguard interfaces. 

        The peer will be owned by the server interface and is connected to the client interface

        :param serverInterface: Interface to add the client to.
        :type serverInterface: Interface
        
        :param clientInterface: Interface that is connected to the server
        :type clientInterface: Interface

        :return: Returns the server peer 
        :rtype: Peer
        """
        return Peer(
            interface=serverInterface,
            peer_interface=clientInterface,
            persistent_keepalive=KEEPALIVE
        )

    @staticmethod
    def createProfile(user: User) -> Profile:
        """
        Create a profile for the given user
        Profile is used to store wireguard and special data of the user.

        :param user: The user to create the profile to.
        :type user: User

        :return: The created profile instance.
        :rtype: Profile
        """
        return Profile(user=user, verified=False)

    @staticmethod
    def makeServerNewName() -> str:
        """
        Provides a unique name for a server interface.
        Creates a name in a form `wg-server{num}`.

        :return: Generated name for the server interface.
        :rtype: str
        """
        names = Interface.objects.filter(interface_type=Interface.SERVER).values_list("name", flat=True)
        nums = [int(re.search(r"\d+", x).group()) for x in names if re.search(r"\d+", x)]
        num = max(nums, default=-1)
        return f"wg-server{num + 1}"
    
    @staticmethod
    def createPeerSnapshot(peer :Peer, endpoint : str, handshake_dt :datetime, rx_bytes : int, tx_bytes : int, serverInterface : Interface) -> PeerSnapshot:
        """
        Creates a PeerSnapshot object for saving peer state. 

        :param peer: The Peer to save its snapshot of its state.
        :type peer: Peer

        :param endpoint: The last endpoint that the peer connected from, will insert None if value is `(none)` 
        :type endpoint: str

        :param handshake_dt: Last time that a wireguard handshake happened. Insert timezone aware datetime with `timezone.make_aware(date)`
        :type handshake_dt: datetime

        :param rx_bytes: The amount of recieved bytes to the peer of the server interface from client interface. Means Upload.
        :type rx_bytes: int

        :param tx_bytes: The amount of sent bytes from the peer of the server interface to client interface. Means Download.
        :type tx_bytes: int

        :param serverInterface: The server interface of this peer. Used to get session number of the server interface.
        :type serverInterface: Interface

        :return: The created PeerSnapshot instance.
        :rtype: PeerSNapshot
        
        """
        return PeerSnapshot(
            peer=peer,
            endpoint=None if endpoint == "(none)" else endpoint,
            latest_handshake=handshake_dt,
            rx_bytes=rx_bytes,
            tx_bytes=tx_bytes,
            session=serverInterface.session_number
        )